language: python
python:
- '2.7'
install:
- pip install -r test_requirements.txt -r requirements.txt
script: ./run_tests.sh
env:
  global:
  - secure: jEaJEI/iUXaNdYB+0qnRVySaqJP53ua7lsnMP/phm4rpXCNa2jhVRwcKuIEusijYpVuc038tI355e8yB7oAcOeysazIDHuAuVr09GclMSencBw5kfObi05fzI6N9ODPt1A91rbmPSJiegIVaSdWdU0tNFSlQmitUyo6GZW3MLCs=
  - secure: NSHD/V/e/JV38Xf2Ec+lL0omVr/0+BEA1BZfhLNOjcx/MLnJwjoLioL2Llv3PplptPbTqwcXXj1qTregvZoc9TudnSBSDx5OgPAkoE9NiKfJmmfvidSEIW+TVK56NjoFHT7W0Khmwtr6bFD4DKx3YFN4v0A0UmE6D9VwHIYsz00=
  - secure: ZJ/IaioL8279+a2H5f1LFJ9mX1tQk8N4qOiDCLZ3ir0vqvWHPEvCWDmVVe4/2caZ1gMGfo/yXCgwwT0EaRE4v1X7ICF46XzmkVAgytnSj1mlLJ63E5ZvBmyAEhpRGtxtPu6momgkyt+nqDl6tlLseiPGZRGNLtSbLRaCHkJAMFU=
  - secure: VyEXk4w/IUx7vy/c4CEpiGXHj495gz1gSUpN89007CSY8a92CsOuKmJBhgs7ygLpiWB5igYnRhi/OS/tO92m0v4Nz8AJG/8TH6e3pShuqO3FWSMOZ3p7c39UhW7D5Xsh5N9z5cbbXv3ZFRrY4uceQlVniZHmGYHdhiP1doN+Cns=
  - secure: YKgk9TDfvTr754aDu52MVKkbIqlQK9BKXCdc8jA2knHXNdpFcvVz86gOqu9KDB7FWq42w4OPgfpQfXmT1gcNF/np8+BHBNW/Nypu7UvQAaME04TRgWJ6j/q2xTBg3oUVGoueh2eh3p/exppBSAhrJXrbIvFGNLbpUvC8VBsaNYE=
